Public Class FrmDiagnosa
    Private Sub FrmDiagnosa_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        txtGejala.Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus ex sed aliquet dignissim. Mauris imperdiet, eros iaculis auctor finibus, mi ex dapibus metus, sit amet sagittis felis elit quis est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam id arcu risus. Etiam ac eros facilisis ipsum congue sollicitudin. Phasellus a velit eget ex feugiat tincidunt. Vestibulum a porta risus. Cras at porttitor dui.
Aliquam laoreet ipsum sit amet ligula rutrum, vitae scelerisque nibh malesuada. Curabitur sodales, ex sed consectetur venenatis, metus augue cursus felis, at varius leo odio ut neque. Suspendisse ac dolor urna. Maecenas et elementum tellus. Nunc facilisis consequat lectus eu suscipit. Nunc luctus urna eget odio semper, at dignissim dolor faucibus. Pellentesque eu nisl volutpat, lacinia eros molestie, pellentesque orci. Integer velit ligula, faucibus ac gravida non, tincidunt facilisis metus. Praesent laoreet, lacus a mollis accumsan, ante magna feugiat lectus, non pretium lorem lorem ut lectus. Duis ultricies vitae felis efficitur porttitor. Mauris mollis enim eu ex posuere, quis iaculis dui pharetra. Vestibulum sit amet viverra felis. Vivamus placerat commodo condimentum. Integer eu porta risus, et rutrum lacus. Etiam sit amet metus vestibulum, vulputate dolor in, blandit nunc. Vestibulum sit amet tortor suscipit, dapibus nisl a, egestas erat.
Sed a ipsum sed leo rhoncus tristique eu ac erat. Nam ultrices pharetra dui, vel porta diam dictum vitae. Praesent diam neque, dignissim consequat sagittis ac, molestie id dui. Nulla pharetra justo eros, quis lobortis dolor rhoncus non. Praesent placerat non risus in egestas. Integer et eleifend libero. Fusce eleifend sem sed ante laoreet pulvinar. Phasellus eros nisl, lacinia vel dui et, semper consectetur metus. In ac urna non justo tincidunt rhoncus id sed sapien. Vivamus sed ligula ornare, scelerisque justo at, aliquam neque. Nullam porta efficitur mi, eget feugiat tellus consectetur eget. Fusce tristique magna eget quam tincidunt fringilla.
Fusce convallis metus id faucibus gravida. Phasellus a velit quis ligula posuere faucibus. Nam nisi purus, euismod vitae turpis et, laoreet finibus felis. Vivamus eget urna nec sem malesuada aliquam. Vivamus suscipit risus libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum quis nisi et efficitur. Donec auctor lacinia luctus. Etiam bibendum euismod urna, id vulputate sapien hendrerit id. Aenean mollis vel nisi imperdiet elementum. Aliquam auctor lorem nec purus aliquet venenatis. Mauris dapibus est mi, ornare semper lacus imperdiet vel.
Vivamus luctus, elit in suscipit porta, metus eros venenatis augue, placerat malesuada lacus nisl non nibh. Ut quis nulla non dui suscipit porta. Nam facilisis enim nec tortor sodales accumsan. Aenean elementum, nulla et ultrices pulvinar, leo lacus sollicitudin tortor, sed luctus libero nibh nec diam. Integer sit amet turpis massa. Donec vulputate nisi quis odio bibendum dignissim. Curabitur in erat est. Duis condimentum lectus at consequat vehicula. Nam eleifend lacinia venenatis. Nullam quis efficitur nunc. Cras urna ipsum, viverra vitae dolor nec, sagittis consectetur diam. Praesent porttitor ligula elit, sed feugiat libero malesuada id. Aliquam tempus auctor condimentum. Mauris efficitur in est vitae dignissim.
Integer arcu mi, lacinia a libero eu, posuere porta ex. Mauris ac fermentum ligula. Maecenas malesuada gravida maximus. Vivamus ornare, neque non porta congue, urna nibh rutrum massa, in efficitur ex velit a nisi. Nullam eu consequat neque. Aenean id ullamcorper turpis, ut rhoncus quam. Fusce faucibus elit magna, in convallis purus luctus at. Sed auctor enim mauris, sed pharetra risus pharetra vitae. Cras nec condimentum dolor. Donec at quam eu quam dapibus rutrum. Praesent eros dolor, suscipit ac risus in, iaculis lacinia justo.
Curabitur diam eros, aliquam iaculis risus sed, dignissim commodo eros. Proin non ex a lectus iaculis ullamcorper ut vel magna. Aliquam sollicitudin pretium dolor in auctor. Nam luctus congue blandit. Etiam lacinia, elit at tempor molestie, lectus quam finibus augue, ut luctus ante lectus sed nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam auctor metus sed massa elementum ullamcorper nec sed nibh.
Vestibulum efficitur imperdiet mi, eu fermentum neque bibendum et. Nullam egestas lectus dui, ut venenatis magna blandit sit amet. Curabitur consectetur dictum consequat. Integer dapibus, dui at semper lacinia, metus libero suscipit magna, sit amet molestie nisl ipsum vel leo. Quisque volutpat, risus sit amet pulvinar luctus, massa purus laoreet orci, ac egestas leo justo at sem. Nam at est vitae est sodales luctus quis id nibh. Proin fringilla nibh est, sed fermentum nulla luctus et. Nullam aliquam, purus in maximus fermentum, risus purus porttitor velit, consectetur vehicula elit metus a dui. Aenean rutrum vulputate libero id tempus.
Fusce velit ipsum, molestie sed urna vitae, scelerisque pulvinar turpis. Fusce sit amet sem pulvinar metus luctus volutpat. Nam at dictum est. Cras facilisis euismod elementum. Donec mollis, justo sed volutpat gravida, massa metus posuere lacus, et luctus purus felis vitae magna. Pellentesque euismod leo ut ex molestie varius. Nunc id fermentum ex. In fringilla metus in elementum vulputate.
Maecenas vel facilisis risus, vel volutpat tortor. Pellentesque vel dolor pretium ligula euismod hendrerit eget non quam. Vestibulum velit dolor, molestie nec consectetur at, venenatis ac nisi. Sed venenatis fringilla nulla nec ultrices. Proin mi mauris, efficitur et magna sed, vestibulum viverra ex. Aenean mollis pulvinar magna, in maximus leo feugiat et. Praesent id ipsum facilisis, hendrerit felis at, laoreet nisl. Nam metus leo, cursus id ultricies vitae, vulputate a urna. Mauris lobortis mi nec elit viverra tristique. Pellentesque a imperdiet est, eget fermentum felis. Ut tortor diam, iaculis eu quam eu, vestibulum consectetur velit. Morbi non tempor lorem. Sed malesuada enim tortor, ac accumsan nisl sollicitudin in."
    End Sub

    Private Sub TxtSuhu_Validated(sender As Object, e As EventArgs) Handles txtSuhu.Validated
        If txtSuhu.Text >= "100" Then

        End If
    End Sub

    Private Sub BtnYa_Click(sender As Object, e As EventArgs) Handles btnYa.Click
        grpSuhu.Visible = True
    End Sub

    Private Sub TxtSuhu_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtSuhu.KeyPress
        If Asc(e.KeyChar) <> 8 Then
            If Asc(e.KeyChar) < 48 Or Asc(e.KeyChar) > 57 Then
                e.Handled = True
            End If
        End If
    End Sub
End Class